kind: pipeline

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test

- name: notify
  image: plugins/slack
  settings:
    channel: general
  when:
    status: [ success, failure ]
